"""
Nifty 500 tickers — hardcoded list so we don't depend on scraping.
Focused on liquid large/mid caps where yfinance data is reliable.
"""

NIFTY500_TICKERS = [
    # Nifty 50 — most liquid
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","ITC.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "AXISBANK.NS","LT.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","BAJFINANCE.NS","WIPRO.NS","HCLTECH.NS",
    "NESTLEIND.NS","POWERGRID.NS","NTPC.NS","TECHM.NS","BAJAJFINSV.NS",
    "ONGC.NS","COALINDIA.NS","TATAMOTORS.NS","ADANIENT.NS","JSWSTEEL.NS",
    "TATASTEEL.NS","HINDALCO.NS","GRASIM.NS","DRREDDY.NS","CIPLA.NS",
    "DIVISLAB.NS","EICHERMOT.NS","HEROMOTOCO.NS","APOLLOHOSP.NS","BPCL.NS",
    "TATACONSUM.NS","BRITANNIA.NS","SHREECEM.NS","INDUSINDBK.NS","ADANIPORTS.NS",
    "SBILIFE.NS","HDFCLIFE.NS","M&M.NS","UPL.NS","BAJAJ-AUTO.NS",

    # Nifty Midcap — more inefficient, more drift
    "MUTHOOTFIN.NS","PIIND.NS","PERSISTENT.NS","COFORGE.NS","LTIM.NS",
    "MPHASIS.NS","OFSS.NS","KPITTECH.NS","TATAELXSI.NS","ZOMATO.NS",
    "NYKAA.NS","DELHIVERY.NS","POLICYBZR.NS","PAYTM.NS","IRCTC.NS",
    "IRFC.NS","RVNL.NS","HAL.NS","BEL.NS","BHEL.NS",
    "AUROPHARMA.NS","TORNTPHARM.NS","ALKEM.NS","IPCALAB.NS","LUPIN.NS",
    "GLAXO.NS","PFIZER.NS","ABBOTINDIA.NS","METROPOLIS.NS","LALPATHLAB.NS",
    "VOLTAS.NS","HAVELLS.NS","CROMPTON.NS","POLYCAB.NS","KEI.NS",
    "ASTRAL.NS","SUPREME.NS","AARTIIND.NS","DEEPAKNTR.NS","GNFC.NS",
]

if __name__ == "__main__":
    print(f"Universe: {len(NIFTY500_TICKERS)} stocks")