"""
NSE universe — liquid large + mid caps with decent yfinance coverage.
Mid/small caps are the real target: less analyst coverage = more drift.
"""

UNIVERSE = [
    # Nifty 50
    "RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS",
    "HINDUNILVR.NS","ITC.NS","SBIN.NS","BHARTIARTL.NS","KOTAKBANK.NS",
    "AXISBANK.NS","LT.NS","ASIANPAINT.NS","MARUTI.NS","SUNPHARMA.NS",
    "TITAN.NS","ULTRACEMCO.NS","BAJFINANCE.NS","WIPRO.NS","HCLTECH.NS",
    "NESTLEIND.NS","POWERGRID.NS","NTPC.NS","TECHM.NS","BAJAJFINSV.NS",
    "ONGC.NS","COALINDIA.NS","JSWSTEEL.NS","TATASTEEL.NS","HINDALCO.NS",
    "GRASIM.NS","DRREDDY.NS","CIPLA.NS","DIVISLAB.NS","EICHERMOT.NS",
    "HEROMOTOCO.NS","APOLLOHOSP.NS","BPCL.NS","TATACONSUM.NS","BRITANNIA.NS",
    "INDUSINDBK.NS","ADANIPORTS.NS","SBILIFE.NS","HDFCLIFE.NS","M&M.NS",
    "BAJAJ-AUTO.NS","ADANIENT.NS","SHREECEM.NS","UPL.NS",
    # Midcap — higher drift potential
    "MUTHOOTFIN.NS","PIIND.NS","PERSISTENT.NS","COFORGE.NS",
    "KPITTECH.NS","TATAELXSI.NS","IRCTC.NS","IRFC.NS",
    "RVNL.NS","HAL.NS","BEL.NS","AUROPHARMA.NS","TORNTPHARM.NS",
    "ALKEM.NS","IPCALAB.NS","LUPIN.NS","VOLTAS.NS","HAVELLS.NS",
    "POLYCAB.NS","KEI.NS","ASTRAL.NS","DEEPAKNTR.NS",
    "METROPOLIS.NS","LALPATHLAB.NS","CROMPTON.NS",
    # Replacements for dead tickers + new additions
    "LTIM.NS","LTTS.NS","ZOMATO.NS","NAUKRI.NS",
    "DMART.NS","DIXON.NS","PAGEIND.NS","TRENT.NS",
    "ANGELONE.NS","CDSL.NS","MCX.NS","MARICO.NS",
    "MPHASIS.NS","OFSS.NS","ABBOTINDIA.NS","GNFC.NS",
]

UNIVERSE_SHORT = [t.replace(".NS", "") for t in UNIVERSE]